{% set name = "mizani" %}
{% set version = "0.14.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28934d91516d922d7cb0382c82a6c513692abc0174c42a50294ae571520633f9

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - setuptools_scm >=6.2
    - tomli
    - wheel
  run:
    - python
    - numpy >=1.23.5
    - scipy >=1.8.0
    - pandas >=2.2.0
    - python-tzdata  # [win]
  run_constrained:
  # Upstream: pyright has an exact version pinning. constraint relaxed to bigger-or-equal.
    - pyright >=1.1.408

test:
  source_files:
    - tests
  imports:
    - mizani
    - mizani._colors
    - mizani._colors._colormaps._maps._segment_function
    - mizani._colors._palettes.brewer
    - mizani._colors._palettes.other
    - mizani._colors.named_colors
    - mizani._colors.utils
    - mizani._datetime
    - mizani._datetime.breaks
    - mizani._datetime.utils
    - mizani._timedelta.breaks
    - mizani._timedelta.utils
    - mizani.bounds
    - mizani.breaks
    - mizani.labels
    - mizani.palettes
    - mizani.scale
    - mizani.transforms
    - mizani.utils
  commands:
    - pip check
    - pytest -vv
  requires:
    - pip
    - pytest
    - pytest-cov

about:
  home: https://github.com/has2k1/mizani
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A scales package for python
  description: |
    Mizani is a scales package for graphics.
    It is written in Python and is based on Hadley Wickham's Scales.
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
