{% set name = "mizani" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d481a4dc673caa9b7cfdc6505b9401f0e9a9f43434d748df0678a1a4017b0e2

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - numpy>=1.19.0
    - backports.zoneinfo  # [py<39]
    - matplotlib-base >=3.5.0
    - pandas >=1.3.5
    - scipy >=1.5.0
    - tzdata

test:
  imports:
    - mizani
    - mizani.external
    - mizani.tests
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - 'mizani/tests/*.py'
  commands:
    - pip check  # [not win]
    - cd mizani && pytest tests -vv

about:
  home: https://github.com/has2k1/mizani
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A scales package for python
  description: |
    Mizani is a scales package for graphics. 
    It is written in Python and is based on Hadley Wickham's Scales.
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
