{% set name = "mizani" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8e0b16627442bda2899e39f834ff004eb49f2da874f01f13aa329d073d6adc5

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - numpy >=1.23.0
    - scipy >=1.7.0
    - pandas >=2.1.0
    - tzdata  # [win]

test:
  imports:
    - mizani
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - "tests"
    - pyproject.toml
  commands:
    - pip check  # [not win]
    - pytest -vv

about:
  home: https://github.com/has2k1/mizani
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A scales package for python
  description: |
    Mizani is a scales package for graphics.
    It is written in Python and is based on Hadley Wickham's Scales.
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
