travis:
  secure:
    BINSTAR_TOKEN: ZYX3f66OWIg95OE+F/gNZ0TAAtsvRYz849GEGO2vve9vWwv7XPlUgMj2cHKGeotOJJBv5CXmgGtdT8QFatXJq1UBfhDoHRjuvsAT2luLFKdIYT8E7uPUxNH8JuGVw8qgJUqycUJL3s8dCUlcnRmcppL8U2ESmaNCLYvGKPaDzRxMik2ECMVJz+NybvnZrAhI6y/i3cpw8kxle9DMKgt+NaycmcWePrsYgCi2NypPIucb8a4inDNXJJ8fxaPSMOEnpYqJ7vTlYUKff0Kf4GutOqrynzCzIgRhE3UgDo8L1op6PHaWlbSKeDt/xpt2bn9HJh7bDdsW4DiVS9QaaUTFhWp5Eu3+GkTQNpwVPJ3IhBkcn5X6oaNsvcmlw0clD5Q5HBIRZ0bGjw4VvxY7yTzo5kFckEHEqj0gxyiOBI7BfVHK0h0zlrAEuknJjUIKJSEN0US6RBNGeYNZfYjRjVRcTwszLn4cJ8q0gSubHkB+Ui76+RQzm8Est5Cqpbh+i+HOfsw0Ip+S+8iBynGFnoVx0cfv3xJC/ppPDwKTUE2eAzI7upRF+cSE+UiGAuKkTjAMiKQ3CnGYIbZx1LzXS5bCqsZPl3ZkYopEqviNhECDQ3Hwb4l2Dn2xKrk8h/mdEruKatNP1IJhr/UrY2HH9aHpw9mqFQSU372axLpxSIj29tA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
