travis:
  secure:
    BINSTAR_TOKEN: wxzNB14NsiGuKq+okA3XtywQLjIxiHr3p5T0xabcMcn+v6eH+1DcCcFxsgMFObPO1ZJ9389wSLTBXBMWN1mV6bXEEJhGP8zA0tn3lVxWIH9hWtBGpNz/l8AipAaXUt5NQEVx4aA7or/VUYIwfBWZbTmzA1vv6tljLbIKNXtaGK4TSo8qiFG1zv0sNcy3sKfjGskdnf2TPDCDxy/lwLIPWe8MjUg83ULdrRzvSDk8uUbV9a+eV4H9Q1RXhddbjO7vgWGBSzYXPhT5n9DMUxSXi+nepWkjS0ZuT1KW5OAbcPrXUmLi6WiPux/YljCW6HSQPBxUagdHa0tG+S61H4Si90db46iJCiDxm8oHVm+jyqdVbG3kqOMnwG2N4uOfv47XH51ZFSGED2Ez5G2A7SQNYqZcpqVYZO8iCzwCYGDdhJiC5sdGwefL7uEBrMzqV1Vped6QbQ4MaQYNA+qBCd+XKE8ZFZiKD+t/XmquT1z8gUAGEy1BGOq39+KiXGxBlkfLz7Uh39ELsdesJZ0iou2qO7Yzc145F5k9GOWhY/pjNfPFQaSuk1orFnXCeIgEWyagoQR1p/ZF5I4KKGK3t279ORWolhVJ43E6CI4etppoSqz39MKU7BcLAbtBiTkE04wjDnMufhiq3cjWSwzbgkaHTB38nzaZq//QC9N8eLdU0E0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
