travis:
  secure:
    BINSTAR_TOKEN: O/bNgU0X052NIeFSp+Q8hfROLzlYL0UKwJ2yXZpVJvJtTTdEOU1UCiAz/mbUGNqz2ZG7K+3iXJkHN2XgB935ygtjYaLzk16bhyXAY0GvVVczSjn/pfX6OaG/49F+ULrc8x69BzPLu4udkw9KOIbwZhV1jvGuowhx3omvtmGlJNUo4yOqJ1DGNLu6W8lHAN4Z07+/2p+mMh1YwP+rr1RkRylHlbXJ8M4rUpf6reEA+aPUiuGk696HkIRIYiR6AXac4dZgvlEneKhBDwwq1jx0oK/5OwTih0RzaI2Cc7jQOdFAmLUYNdxavNcXu7Bbpqk3tKxMo54Si2b3/ej2mwcBSHzvyIzwC80DrzskEOBjkvol1ydcAc9ogMGy45OV2XvHARVSe2NgKiCEG2zxE0lJ3nkJ7xv1oGBrMCO23gpixjUPzyfYt+Lvubo0Da9WFArPQaVWUwaeJu9E4nDTYaZ7ZYEo0VvAAzTuGWpde85CVlB8WY8175ahw8Ee1Hr9pfM18lUD9BHjDhMyziCJWUG1bBI3+pRqkxBcD71ZTv5Gr5SUVtf8h7OT9jGCKgKuOk6V6pbOj3G6vocYHo0ilaDoCKzjEDajqgwfmL1bflZRcLi5p4OUrv+Ydw0mP5hIeKRMd8ufIsbHt0BNqNqEnWFIXlVpf1Aon2dwWNohb4YXmxY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
