travis:
  secure:
    BINSTAR_TOKEN: AXbe7gvmmL6PPwOE7clT2VuATPZUi3IlWCxtWZHXyCK+5gWm6pvuIjXg+cTr+gyGqUTqZ5LigdsnFl5CwiQ/F+acfAXYBQbTP9Q8lrkKG8g6ml2R98Oj836O/T3yph1BtbCg94QES/TinRVJ8HmA80VFjOq2DF5zm6i3LBiKNpgsWJ1ocjuzJRV5lk80RfuHpE8INj+fpLBP+eC3v+prCOTvtQOldHN2G7gIot5nRl+nU2C8Oy/371AHn1y6Yxy5pLb/l6p14A/sOPXCS5ILxMShKbz3iMHADVaXHpB4lNoHOJPkpM0AnY3nZpxuSeMKvcf0REOyJX0lHzk1BavYPWmiKwR9RyLYDx6JDgN5WJjZVMkLyYs1+o7U73k6TMtDPScxrtxQNMEaNRV0ktZcp5GUHhbBQVPT6k6nwuSizFfs6JaXuOSL/NIPhzc0elxqX/cf7A4L+6ePpmyA45wz1YvWw5uHQgMZmxoVxPN2uiao/hAHJIXWP1VIQOIsfFY9o5ZPNKowZX0mlBc3RIxMOcm+S+xqrc97WOaTqySwkN4rbJrgtDvEMAcNLfj4zmmXIB67WJ/PJgjKOAbttlRT128403h+fAoN2ifYciIPehotlxGZJ2QFI4xRrEC2KqfFsKbTR8rleDjqWMXXYiQzuYVskGoWPwLdcFt03Z1C1ao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
